### ISSUE TITLE
Dependencies not declared: Minion and Mojar::Util

### ISSUE THREAD

**Issue by andk** [niczero/minion-backend-storable#1]
They are used in
https://metacpan.org/source/NICZERO/Minion-Backend-File-5.082/test/10-file.t#L9
and
https://metacpan.org/source/NICZERO/Minion-Backend-File-5.082/test/10-file.t#L515
respectively.

Sample fail reports:

http://www.cpantesters.org/cpan/report/70277864
http://www.cpantesters.org/cpan/report/70277877

HTH&&Thanks,

PS: of minor importance, but could you explain the rationale behind renaming t/ to test/ ? I must have missed some discussion about it.

**Comment by niczero** [comment]
Thanks for the report; always appreciated.  The first problem was already fixed (thanks travisci).  The second problem I've just fixed by removing the line, a hangover from some debug work.

For the directory names, either they should all have single-char names or they should all have readable names.  I opted for the latter.

cheers n beers,
Nic
